<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Main.aspx.cs" Inherits="SignalRChat.Main" %>

<!DOCTYPE html>
<html>
<head>
    <title>chat</title>
    <link href="Content/Main.css" rel="stylesheet" />
    
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/date.format.js"></script>

    <!--EmojiOneArea -->
    <link href="Content/emojionearea.min.css" rel="stylesheet" />
    <script src="Scripts/emojionearea.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Jquery slimScroll -->
    <script type="text/javascript" src="Scripts/jquery.slimscroll.min.js"></script>

    <script type="text/javascript">
        $(function () {

            // Declare a proxy to reference the hub.

            var chatHub = $.connection.chatHub;
            registerClientMethods(chatHub);
            // Start Hub
            $.connection.hub.start().done(function () {

                registerEvents(chatHub)

            });
            function registerClientMethods(chatHub) {


                // Calls when user successfully logged in
                chatHub.client.onConnected = function (id, userName, allUsers, messages, times) {

                    $('#hdId').val(id);
                    $('#hdUserName').val(userName);
                    $('#spanUser').html(userName);

                    // Add All Users
                    for (i = 0; i < allUsers.length; i++) {

                        AddUser(chatHub, allUsers[i].ConnectionId, allUsers[i].UserName, allUsers[i].UserImage, allUsers[i].LoginTime);
                    }

                    // Add Existing Messages
                    for (i = 0; i < messages.length; i++) {
                        AddMessage(messages[i].UserName, messages[i].Message, messages[i].Time, messages[i].UserImage);

                    }
                }

                // On New User Connected
                chatHub.client.onNewUserConnected = function (id, name, UserImage, loginDate) {
                    AddUser(chatHub, id, name, UserImage, loginDate);
                }

                // On User Disconnected
                chatHub.client.onUserDisconnected = function (id, userName) {

                    $('#Div' + id).remove();

                    var ctrId = 'private_' + id;
                    $('#' + ctrId).remove();


                    var disc = $('<div class="disconnect">"' + userName + '" logged off.</div>');

                    $(disc).hide();
                    $('#divusers').prepend(disc);
                    $(disc).fadeIn(200).delay(2000).fadeOut(200);

                }

                chatHub.client.messageReceived = function (userName, message, time, userimg) {

                    AddMessage(userName, message, time, userimg);

                    // Display Message Count and Notification
                    var CurrUser1 = $('#hdUserName').val();
                    if (CurrUser1 != userName) {

                        var msgcount = $('#MsgCountMain').html();
                        msgcount++;
                        $("#MsgCountMain").html(msgcount);
                        $("#MsgCountMain").attr("title", msgcount + ' New Messages');
                        var Notification = 'New Message From ' + userName;
                        IntervalVal = setInterval("ShowTitleAlert('SignalR Chat App', '" + Notification + "')", 800);

                    }
                }


                chatHub.client.sendPrivateMessage = function (windowId, fromUserName, message, userimg, CurrentDateTime) {

                    var ctrId = 'private_' + windowId;
                    if ($('#' + ctrId).length == 0) {

                        OpenPrivateChatBox(chatHub, windowId, ctrId, fromUserName, userimg);

                    }

                    var CurrUser = $('#hdUserName').val();
                    var Side = 'right';
                    var TimeSide = 'left';

                    if (CurrUser == fromUserName) {
                        Side = 'left';
                        TimeSide = 'right';

                    }
                    else {
                        var Notification = 'New Message From ' + fromUserName;
                        IntervalVal = setInterval("ShowTitleAlert('SignalR Chat App', '" + Notification + "')", 800);

                        var msgcount = $('#' + ctrId).find('#MsgCountP').html();
                        msgcount++;
                        $('#' + ctrId).find('#MsgCountP').html(msgcount);
                        $('#' + ctrId).find('#MsgCountP').attr("title", msgcount + ' New Messages');
                    }

                    var divChatP = '<div class="direct-chat-msg ' + Side + '">' +
                        '<div class="direct-chat-info clearfix">' +
                        '<span class="direct-chat-name pull-' + Side + '">' + fromUserName + '</span>' +
                        '<span class="direct-chat-timestamp pull-' + TimeSide + '"">' + CurrentDateTime + '</span>' +
                        '</div>' +

                        ' <img class="direct-chat-img" src="' + userimg + '" alt="Message User Image">' +
                        ' <div class="direct-chat-text" >' + message + '</div> </div>';

                    $('#' + ctrId).find('#divMessage').append(divChatP);

                    // Apply Slim Scroll Bar in Private Chat Box
                    var ScrollHeight = $('#' + ctrId).find('#divMessage')[0].scrollHeight;
                    $('#' + ctrId).find('#divMessage').slimScroll({
                        height: ScrollHeight
                    });
                }

            }

            function AddUser(chatHub, id, name, UserImage, date) {

                var userId = $('#hdId').val();

                var code, Clist;
                if (userId == id) {

                    code = $('<div class="box-comment">' +
                        '<img class="img-circle img-sm" src="images/' + UserImage + '" alt="User Image" />' +
                        ' <div class="comment-text">' +
                        '<span class="username">' + name + '<span class="text-muted pull-right">' + date + '</span>  </span></div></div>');


                    Clist = $(
                        '<li style="background:#494949;">' +
                        '<a href="#">' +
                        '<img class="contacts-list-img" src="' + UserImage + '" alt="User Image" />' +

                        ' <div class="contacts-list-info">' +
                        ' <span class="contacts-list-name" id="' + id + '">' + name + ' <small class="contacts-list-date pull-right">' + date + '</small> </span>' +
                        ' <span class="contacts-list-msg">How have you been? I was...</span></div></a > </li >');

                }
                else {

                    code = $('<div class="box-comment" id="Div' + id + '">' +
                        '<img class="img-circle img-sm" src="' + UserImage + '" alt="User Image" />' +
                        ' <div class="comment-text">' +
                        '<span class="username">' + '<a id="' + id + '" class="user" >' + name + '<a>' + '<span class="text-muted pull-right">' + date + '</span>  </span></div></div>');


                    Clist = $(
                        '<li>' +
                        '<a href="#">' +
                        '<img class="contacts-list-img" src="' + UserImage + '" alt="User Image" />' +

                        ' <div class="contacts-list-info">' +
                        '<span class="contacts-list-name" id="' + id + '">' + name + ' <small class="contacts-list-date pull-right">' + date + '</small> </span>' +
                        ' <span class="contacts-list-msg">How have you been? I was...</span></div></a > </li >');


                    var UserLink = $('<a id="' + id + '" class="user" >' + name + '<a>');

                    $(code).click(function () {

                        var id = $(UserLink).attr('id');

                        if (userId != id) {
                            var ctrId = 'private_' + id;
                            OpenPrivateChatBox(chatHub, id, ctrId, name);

                        }

                    });

                    var link = $('<span class="contacts-list-name" id="' + id + '">');
                    $(Clist).click(function () {

                        var id = $(link).attr('id');

                        if (userId != id) {
                            var ctrId = 'private_' + id;
                            OpenPrivateChatBox(chatHub, id, ctrId, name);

                        }

                    });

                }

                $("#divusers").append(code);

                $("#ContactList").append(Clist);

            }

            // Reset Message Counter on Hover
            //$("#divChatWindow").mouseover(function () {

            //    $("#MsgCountMain").html('0');
            //    $("#MsgCountMain").attr("title", '0 New Messages');
            //});

            // Diplay Image Preview on File Upload 
            //$(document).on('change', '#<%# FileUpload1.ClientID%>', function (e) {

                 //  var tmppath = URL.createObjectURL(e.target.files[0]);
                //   $("#ImgDisp").attr('src', tmppath);

              // });



               // Stop Title Alert
               window.onfocus = function (event) {
                   if (event.explicitOriginalTarget === window) {

                       clearInterval(IntervalVal);
                       document.title = 'Chat Bot';
                   }
               }


           });

    </script>
</head>

<body>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  

    <!-- char-area -->
    <section class="message-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="chat-area">
                        <!-- chatlist -->
                        <div class="chatlist">
                            <div class="modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="chat-header">
                                        <div class="msg-search">
                                            <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Search" aria-label="search">
                                            <a class="add" href="#">
                                                <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/add.svg" alt="add"></a>
                                        </div>

                                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                                            <li class="nav-item" role="presentation">
                                                <button class="nav-link active" id="Open-tab" data-bs-toggle="tab" data-bs-target="#Open" type="button" role="tab" aria-controls="Open" aria-selected="true">Common Room</button>
                                            </li>
                                            <li class="nav-item" role="presentation">
                                                <button class="nav-link" id="Closed-tab" data-bs-toggle="tab" data-bs-target="#Closed" type="button" role="tab" aria-controls="Closed" aria-selected="false">Private</button>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="modal-body">
                                        <!-- chat-list -->
                                        <div class="chat-lists">
                                            <div class="tab-content" id="myTabContent">
                                                <div class="tab-pane fade show active" id="Open" role="tabpanel" aria-labelledby="Open-tab">
                                                    <!-- chat-list -->
                                                    <div class="chat-list">
                                                        <a href="#" class="d-flex align-items-center">
                                                            <div class="flex-shrink-0">
                                                                <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/user.png" alt="user img">
                                                                <span class="active"></span>
                                                            </div>
                                                            <div class="flex-grow-1 ms-3">
                                                                <h3>Mehedi Hasan</h3>
                                                                <p>front end developer</p>
                                                            </div>
                                                        </a>                                        
                                                    </div>
                                                    <!-- chat-list -->
                                                </div>
                                                <div class="tab-pane fade" id="Closed" role="tabpanel" aria-labelledby="Closed-tab">

                                                    <!-- chat-list -->
                                                    <div class="chat-list">
                                                        <a href="#" class="d-flex align-items-center">
                                                            <div class="flex-shrink-0">
                                                                <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/user.png" alt="user img">
                                                                <span class="active"></span>
                                                            </div>
                                                            <div class="flex-grow-1 ms-3">
                                                                <h3>Mehedi Hasan</h3>
                                                                <p>front end developer</p>
                                                            </div>
                                                        </a>
                                                    
                                                    </div>
                                                    <!-- chat-list -->
                                                </div>
                                            </div>

                                        </div>
                                        <!-- chat-list -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- chatlist -->



                        <!-- chatbox -->
                        <div class="chatbox">
                            <div class="modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="msg-head">
                                        <div class="row">
                                            <div class="col-8">
                                                <div class="d-flex align-items-center">
                                                    <span class="chat-icon">
                                                        <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/arroleftt.svg" alt="image title"></span>
                                                    <div class="flex-shrink-0">
                                                        <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/user.png" alt="user img">
                                                    </div>
                                                    <div class="flex-grow-1 ms-3">
                                                        <h3>Mehedi Hasan</h3>
                                                        <p>front end developer</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <ul class="moreoption">
                                                    <li class="navbar nav-item dropdown">
                                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                                                        <ul class="dropdown-menu">
                                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                                            <li>
                                                                <hr class="dropdown-divider">
                                                            </li>
                                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="modal-body">
                                        <div class="msg-body">
                                            <ul>
                                                <li class="sender">
                                                    <p>Hey, Are you there? </p>
                                                    <span class="time">10:06 am</span>
                                                </li>                                               
                                                <li>
                                                    <div class="divider">
                                                        <h6>Yesterday</h6>
                                                    </div>
                                                </li>
                                                <li class="repaly">
                                                    <p>yes!</p>
                                                    <span class="time">10:20 am</span>
                                                </li>

                                            </ul>
                                        </div>
                                    </div>


                                    <div class="send-box">
                                        <form action="">
                                            <input type="text" class="form-control" aria-label="message…" placeholder="Write message…">

                                            <button type="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Send</button>
                                        </form>

                                        <div class="send-btns">
                                            <div class="attach">
                                                <div class="button-wrapper">
                                                    <span class="label">
                                                        <img class="img-fluid" src="https://mehedihtml.com/chatbox/assets/img/upload.svg" alt="image title">
                                                        attached file 
                                                    </span>
                                                    <input type="file" name="upload" id="upload" class="upload-box" placeholder="Upload File" aria-label="Upload File">
                                                </div>

                                                <select class="form-control" id="exampleFormControlSelect1">
                                                    <option>Select template</option>
                                                    <option>Template 1</option>
                                                    <option>Template 2</option>
                                                </select>

                                                <div class="add-apoint">
                                                    <a href="#" data-toggle="modal" data-target="#exampleModal4">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16" fill="none">
                                                            <path d="M8 16C3.58862 16 0 12.4114 0 8C0 3.58862 3.58862 0 8 0C12.4114 0 16 3.58862 16 8C16 12.4114 12.4114 16 8 16ZM8 1C4.14001 1 1 4.14001 1 8C1 11.86 4.14001 15 8 15C11.86 15 15 11.86 15 8C15 4.14001 11.86 1 8 1Z" fill="#7D7D7D" />
                                                            <path d="M11.5 8.5H4.5C4.224 8.5 4 8.276 4 8C4 7.724 4.224 7.5 4.5 7.5H11.5C11.776 7.5 12 7.724 12 8C12 8.276 11.776 8.5 11.5 8.5Z" fill="#7D7D7D" />
                                                            <path d="M8 12C7.724 12 7.5 11.776 7.5 11.5V4.5C7.5 4.224 7.724 4 8 4C8.276 4 8.5 4.224 8.5 4.5V11.5C8.5 11.776 8.276 12 8 12Z" fill="#7D7D7D" />
                                                        </svg>
                                                        Appoinment</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- chatbox -->


                </div>
            </div>
        </div>
        <span id="time"></span>
        <input id="hdId" type="hidden" />
        <input id="PWCount" type="hidden" value="info" />
        <input id="hdUserName" type="hidden" />

    </section>
    <!-- char-area -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        jQuery(document).ready(function () {

            $(".chat-list a").click(function () {
                $(".chatbox").addClass('showbox');
                return false;
            });

            $(".chat-icon").click(function () {
                $(".chatbox").removeClass('showbox');
            });


        });
    </script>

</body>
</html>
